import React, { useState, useEffect, useRef } from 'react';
import { Volume2, Download, X, Loader, Play, Pause } from 'lucide-react';
import { generateVoiceover } from '../../lib/voiceoverService';
import { useToast } from '../../contexts/ToastContext';

interface VoiceoverGeneratorProps {
  onClose: () => void;
  initialText?: string;
}

const VOICE_OPTIONS = [
  { id: '21m00Tcm4TlvDq8ikWAM', name: 'Rachel', description: 'Calm, natural female voice' },
  { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Bella', description: 'Soft, expressive female voice' },
  { id: 'MF3mGyEYCl7XYWbV9V6O', name: 'Elli', description: 'Young, energetic female voice' },
  { id: 'AZnzlk1XvdvUeBnXmlld', name: 'Domi', description: 'Strong, confident female voice' },
  { id: 'TxGEqnHWrfWFTfGW9XjX', name: 'Josh', description: 'Deep, warm male voice' },
  { id: 'VR6AewLTigWG4xSOukaG', name: 'Arnold', description: 'Strong, authoritative male voice' },
  { id: 'pNInz6obpgDQGcFmaJgB', name: 'Adam', description: 'Deep, natural male voice' },
  { id: 'yoZ06aMxZJJ28mfd3POQ', name: 'Sam', description: 'Clear, professional male voice' },
  { id: 'CwhRBWXzGAHq8TQ4Fs17', name: 'Roger', description: 'Mature, confident male voice' },
  { id: 'IKne3meq5aSn9XLyUdCD', name: 'Charlie', description: 'Casual, friendly male voice' },
];

export const VoiceoverGenerator: React.FC<VoiceoverGeneratorProps> = ({ onClose, initialText = '' }) => {
  const { showToast } = useToast();
  const [text, setText] = useState(initialText);
  const [isGenerating, setIsGenerating] = useState(false);
  const [audioBlob, setAudioBlob] = useState<Blob | null>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [selectedVoice, setSelectedVoice] = useState(VOICE_OPTIONS[0].id);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    if (initialText && !hasAutoGenerated) {
      setText(initialText);
      setHasAutoGenerated(true);
      setTimeout(() => {
        handleGenerate(initialText);
      }, 100);
    }
  }, [initialText, hasAutoGenerated]);

  useEffect(() => {
    return () => {
      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
      }
    };
  }, [audioUrl]);

  const handleGenerate = async (customText?: string) => {
    const textToUse = customText || text.trim();

    if (!textToUse) {
      showToast('warning', 'Enter text', 'Please enter the text you want to convert to speech');
      return;
    }

    if (isGenerating) {
      console.log('🚫 Generation already in progress');
      return;
    }

    console.log('🎤 Starting voiceover generation:', textToUse);
    setIsGenerating(true);

    try {
      showToast('info', 'Generating Voice', 'Creating your voiceover with ElevenLabs...');

      const blob = await generateVoiceover({
        text: textToUse,
        voiceId: selectedVoice
      });

      if (audioUrl) {
        URL.revokeObjectURL(audioUrl);
      }

      const url = URL.createObjectURL(blob);
      setAudioBlob(blob);
      setAudioUrl(url);
      showToast('success', 'Voiceover Ready!', 'Your audio has been generated successfully');
    } catch (error: any) {
      console.error('Voiceover generation error:', error);
      showToast('error', 'Generation Failed', error.message || 'Unable to generate voiceover. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const togglePlayPause = () => {
    if (!audioRef.current || !audioUrl) return;

    if (isPlaying) {
      audioRef.current.pause();
      setIsPlaying(false);
    } else {
      audioRef.current.play();
      setIsPlaying(true);
    }
  };

  const handleDownload = () => {
    if (!audioBlob) return;

    const url = URL.createObjectURL(audioBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'voiceover.mp3';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('success', 'Downloaded', 'Audio file saved successfully');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-2xl bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 rounded-2xl shadow-2xl border border-white/10 animate-scale-in">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full hover:bg-white/10 transition-colors group z-10"
        >
          <X className="w-5 h-5 text-gray-400 group-hover:text-white" />
        </button>

        <div className="p-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-gradient-to-br from-teal-500 to-blue-500 rounded-xl">
              <Volume2 className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white">AI Voiceover Generator</h2>
              <p className="text-sm text-gray-400">Convert your text to natural speech</p>
            </div>
          </div>

          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Select Voice
              </label>
              <select
                value={selectedVoice}
                onChange={(e) => setSelectedVoice(e.target.value)}
                className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-teal-500 cursor-pointer"
              >
                {VOICE_OPTIONS.map((voice) => (
                  <option key={voice.id} value={voice.id} className="bg-gray-800">
                    {voice.name} - {voice.description}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Enter Text
              </label>
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Type or paste the text you want to convert to speech..."
                className="w-full h-40 px-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-teal-500 resize-none"
                maxLength={5000}
              />
              <div className="flex justify-between items-center mt-2">
                <span className="text-sm text-gray-400">{text.length} / 5000 characters</span>
              </div>
            </div>

            {audioUrl && (
              <div className="bg-white/5 border border-white/10 rounded-xl p-6">
                <audio
                  ref={audioRef}
                  src={audioUrl}
                  onEnded={() => setIsPlaying(false)}
                  className="hidden"
                />
                <div className="flex items-center gap-4">
                  <button
                    onClick={togglePlayPause}
                    className="w-14 h-14 bg-teal-500 hover:bg-teal-600 rounded-full flex items-center justify-center transition-colors"
                  >
                    {isPlaying ? (
                      <Pause className="w-6 h-6 text-white" />
                    ) : (
                      <Play className="w-6 h-6 text-white ml-1" />
                    )}
                  </button>
                  <div className="flex-1">
                    <p className="text-white font-medium mb-1">Generated Voiceover</p>
                    <p className="text-sm text-gray-400">Click play to listen</p>
                  </div>
                </div>
              </div>
            )}

            <div className="flex gap-3">
              <button
                onClick={() => handleGenerate()}
                disabled={isGenerating || !text.trim()}
                className="flex-1 px-6 py-3 bg-gradient-to-r from-teal-500 to-blue-500 hover:from-teal-600 hover:to-blue-600 disabled:from-gray-600 disabled:to-gray-600 text-white rounded-xl font-semibold transition-all disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <Loader className="w-5 h-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Volume2 className="w-5 h-5" />
                    Generate Voiceover
                  </>
                )}
              </button>

              {audioBlob && (
                <button
                  onClick={handleDownload}
                  className="px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-semibold transition-all flex items-center gap-2"
                >
                  <Download className="w-5 h-5" />
                  Download
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
